const shared = [
  ['FOOD', 'What is my favourite food?', ['Pizza', 'Burger', 'Momos', 'Biryani']],
  ['FOOD', 'What is my comfort food?', ['Noodles', 'Fries', 'Ice cream', 'Dal rice']],
  ['FOOD', 'What snack do I reach for first?', ['Chips', 'Popcorn', 'Chocolate', 'Fruit']],
  ['FOOD', 'What drink do I order most often?', ['Coffee', 'Tea', 'Lemonade', 'Milkshake']],
  ['FOOD', 'What dessert can I never say no to?', ['Cake', 'Brownie', 'Gulab jamun', 'Donut']],
  ['FOOD', 'What food do I dislike the most?', ['Mushrooms', 'Spicy food', 'Olives', 'Seafood']],
  ['FOOD', 'What would I pick for a midnight snack?', ['Pizza', 'Cereal', 'Toast', 'Maggie']],
  ['FOOD', 'What is my favourite breakfast?', ['Pancakes', 'Paratha', 'Eggs', 'Poha']],
  ['PERSONALITY', 'What always makes me happy?', ['A good laugh', 'A nap', 'A compliment', 'Music']],
  ['PERSONALITY', 'What is my biggest fear?', ['Heights', 'Being late', 'Spiders', 'Missing out']],
  ['PERSONALITY', 'What annoys me the most?', ['Slow replies', 'Loud chewing', 'Traffic', 'Mess']],
  ['PERSONALITY', 'How do I recharge after a long day?', ['Alone time', 'Talking', 'A walk', 'Sleeping']],
  ['PERSONALITY', 'What is my love language?', ['Quality time', 'Words', 'Gifts', 'Acts of service']],
  ['PERSONALITY', 'What am I most proud of?', ['My kindness', 'My work', 'My growth', 'My courage']],
  ['PERSONALITY', 'What compliment do I secretly love?', ['You are funny', 'You look good', 'You are smart', 'You are thoughtful']],
  ['PERSONALITY', 'What kind of friend am I?', ['The planner', 'The therapist', 'The funny one', 'The spontaneous one']],
  ['HABITS', 'What is my weirdest habit?', ['Talking to myself', 'Checking my phone', 'Making lists', 'Singing randomly']],
  ['HABITS', 'What do I do when I am stressed?', ['Clean', 'Snack', 'Go quiet', 'Overthink']],
  ['HABITS', 'What time am I usually awake?', ['Early bird', 'Around 8', 'Late morning', 'After noon']],
  ['HABITS', 'What do I always carry with me?', ['Lip balm', 'Headphones', 'Snacks', 'A charger']],
  ['HABITS', 'What am I most likely to be late for?', ['Everything', 'Breakfast', 'A party', 'Nothing']],
  ['HABITS', 'What is my screen-time weakness?', ['Short videos', 'Shopping', 'Games', 'Messages']],
  ['HABITS', 'What do I do before bed?', ['Scroll', 'Read', 'Plan tomorrow', 'Watch something']],
  ['HABITS', 'What phrase do I say too often?', ['Honestly', 'Wait what', 'I know right', 'No way']],
  ['MEMORIES', 'What is my favourite memory with you?', ['Our first chat', 'That trip', 'A silly night', 'A celebration']],
  ['MEMORIES', 'Where did we first meet?', ['School', 'Work', 'Online', 'Through a friend']],
  ['MEMORIES', 'What was our funniest moment?', ['The photo', 'The trip', 'The mistake', 'The surprise']],
  ['MEMORIES', 'What do I remember best about us?', ['The laughs', 'The talks', 'The adventures', 'The food']],
  ['MEMORIES', 'What was my favourite childhood activity?', ['Drawing', 'Sports', 'Video games', 'Reading']],
  ['MEMORIES', 'What was my favourite school subject?', ['Art', 'Science', 'History', 'English']],
  ['MEMORIES', 'What place do I want to revisit?', ['The beach', 'A city', 'My hometown', 'The mountains']],
  ['MEMORIES', 'What is a moment I never want to forget?', ['A birthday', 'A trip', 'A win', 'A family day']],
  ['FUNNY', 'What would I do first in a zombie apocalypse?', ['Hide', 'Make a plan', 'Call you', 'Panic']],
  ['FUNNY', 'What am I most likely to accidentally break?', ['My phone', 'A glass', 'A promise', 'The silence']],
  ['FUNNY', 'What would my silly superpower be?', ['Always finding food', 'Perfect naps', 'Knowing lyrics', 'Finding lost things']],
  ['FUNNY', 'What would I bring to a deserted island?', ['Snacks', 'Wi-Fi', 'A friend', 'A pillow']],
  ['FUNNY', 'What is my most dramatic reaction?', ['A tiny spider', 'No Wi-Fi', 'A surprise', 'A bad haircut']],
  ['FUNNY', 'What would I win an award for?', ['Overthinking', 'Being late', 'Making jokes', 'Eating snacks']],
  ['FUNNY', 'What animal matches my energy?', ['Cat', 'Golden retriever', 'Koala', 'Penguin']],
  ['FUNNY', 'What is my most used emoji?', ['😂', '😭', '❤️', '✨']],
  ['FRIENDSHIP', 'What makes a great friend to me?', ['Honesty', 'Fun', 'Support', 'All of these']],
  ['FRIENDSHIP', 'What do I value most in a friendship?', ['Trust', 'Loyalty', 'Laughter', 'Time together']],
  ['FRIENDSHIP', 'What would I do for a friend in need?', ['Call them', 'Show up', 'Send food', 'Listen']],
  ['FRIENDSHIP', 'What kind of plans do I prefer?', ['Cozy at home', 'A night out', 'A day trip', 'Surprise plans']],
  ['FRIENDSHIP', 'How quickly do I reply to friends?', ['Instantly', 'When free', 'Later', 'With a voice note']],
  ['BEST FRIEND', 'What do I always tell my best friend?', ['Everything', 'Only the funny stuff', 'My plans', 'My worries']],
  ['BEST FRIEND', 'What would our perfect hangout be?', ['Movie night', 'Food crawl', 'Long drive', 'Shopping']],
  ['BEST FRIEND', 'What can my best friend tell from my face?', ['I am hungry', 'I am tired', 'I am lying', 'I need a hug']],
  ['BEST FRIEND', 'What is our unofficial tradition?', ['Photos', 'Late chats', 'Inside jokes', 'Sharing food']],
  ['BEST FRIEND', 'What would I never hide from my best friend?', ['A secret', 'A feeling', 'A snack', 'A bad idea']],
  ['COUPLE', 'What is my ideal date?', ['Dinner', 'A long drive', 'A picnic', 'A movie night']],
  ['COUPLE', 'What makes me feel loved?', ['Hugs', 'Small surprises', 'Time together', 'Kind words']],
  ['COUPLE', 'What do I do when I am upset?', ['Go quiet', 'Talk it out', 'Need a hug', 'Take a walk']],
  ['COUPLE', 'What is my favourite couple activity?', ['Cooking', 'Travelling', 'Watching shows', 'Trying new places']],
  ['COUPLE', 'What is my dream romantic getaway?', ['Beach', 'Mountains', 'Paris', 'A cozy cabin']],
  ['CRUSH', 'What catches my attention first?', ['A smile', 'Good humour', 'Kindness', 'Confidence']],
  ['CRUSH', 'What is my ideal first date?', ['Coffee', 'A walk', 'Dinner', 'Arcade games']],
  ['CRUSH', 'What makes someone instantly attractive?', ['Good conversation', 'Eye contact', 'Being thoughtful', 'Being funny']],
  ['CRUSH', 'How do I act around a crush?', ['Talk more', 'Get shy', 'Make jokes', 'Act normal']],
  ['CRUSH', 'What message would make me smile?', ['Thinking of you', 'A funny meme', 'Good morning', 'I miss you']],
  ['FAMILY', 'What do I love doing with family?', ['Eating together', 'Watching films', 'Talking', 'Travelling']],
  ['FAMILY', 'What role do I play at family gatherings?', ['The helper', 'The comedian', 'The quiet one', 'The photographer']],
  ['FAMILY', 'What family food feels like home?', ['A curry', 'A special dessert', 'Sunday lunch', 'Street food']],
  ['FAMILY', 'What do I call my family most for?', ['Advice', 'Laughs', 'Food', 'Comfort']],
  ['FAMILY', 'What family tradition do I love?', ['Celebrations', 'Trips', 'Game nights', 'Big meals']],
]

export const questionBank = shared.map(([category, question, options], index) => ({
  category,
  relationshipType: ['FRIENDSHIP', 'BEST FRIEND', 'COUPLE', 'CRUSH', 'FAMILY'].includes(category) ? category.toLowerCase().replace(' ', '-') : 'all',
  question,
  options,
  correctAnswer: index % 4,
  active: true,
}))
